(defun test_BFS () (cond 
            ((not (equal (BFS '(ROOT)) '(ROOT))) nil)
            ((not (equal (BFS '((((L E) F) T))) '(T F L E))) nil)
            ((not (equal (BFS '((R (I (G (H T)))))) '(R I G H T))) nil)
            ((not (equal (BFS '(((A (B)) C (D)))) '(C A D B))) nil)
            ((not (equal (BFS '((T (H R E) E))) '(T E H R E))) nil)
            ((not (equal (BFS '((A ((C ((E) D)) B)))) '(A B C D E))) nil)
			(t t)
		)
)

(defun test_DFS () (cond 
			((not (equal (DFS '(NIL NIL NIL NIL) NIL) '((NIL NIL NIL NIL) (T T NIL NIL) (NIL T NIL NIL) (T T T NIL) (NIL NIL T NIL) (T NIL T T) (NIL NIL T T) (T T T T)))) nil)
            ((not (equal (DFS '(T T NIL NIL) '((NIL NIL NIL NIL) (T T NIL NIL) (NIL T NIL NIL))) 'NIL)) nil)
            ((not (equal (DFS '(NIL T NIL NIL) '((NIL NIL NIL NIL) (T T NIL NIL))) '((NIL NIL NIL NIL) (T T NIL NIL) (NIL T NIL NIL) (T T T NIL) (NIL NIL T NIL) (T NIL T T) (NIL NIL T T) (T T T T)))) nil)
            ((not (equal (MULT-DFS '((T T NIL NIL)) '((NIL NIL NIL NIL))) '((NIL NIL NIL NIL) (T T NIL NIL) (NIL T NIL NIL) (T T T NIL) (NIL NIL T NIL) (T NIL T T) (NIL NIL T T) (T T T T)))) nil)
            ((not (equal (MULT-DFS '((T T NIL NIL) (T T T NIL) (T T NIL T)) '((NIL NIL NIL NIL) (T T NIL NIL) (NIL T NIL NIL))) '((NIL NIL NIL NIL) (T T NIL NIL) (NIL T NIL NIL) (T T T NIL) (NIL NIL T NIL) (T NIL T T) (NIL NIL T T) (T T T T)))) nil)
            ((not (equal (ON-PATH '(T T T T) '((NIL NIL NIL NIL) (T T NIL NIL) (NIL T NIL NIL) (T T T NIL) (NIL NIL T NIL) (T NIL T T) (NIL NIL T T))) 'NIL)) nil)
            ((not (equal (ON-PATH '(T NIL T T) '((NIL NIL NIL NIL) (T T NIL NIL) (NIL T NIL NIL) (T T T NIL) (NIL NIL T NIL) (T NIL T T) (NIL NIL T T))) 'T)) nil)
            ((not (equal (SUCC-FN '(NIL T NIL NIL)) '((T T NIL NIL) (T T T NIL) (T T NIL T)))) nil)
            ((not (equal (SUCC-FN '(NIL NIL NIL NIL)) '((T T NIL NIL)))) nil)
            ((not (equal (NEXT-STATE '(NIL NIL NIL NIL) 'd) 'NIL)) nil)
            ((not (equal (NEXT-STATE '(NIL NIL NIL NIL) 'b) '(T T NIL NIL))) nil)
            ((not (equal (NEXT-STATE '(T T T NIL) 'h) 'NIL)) nil)
            ((not (equal (NEXT-STATE '(T T NIL NIL) 'p) 'NIL)) nil)
            ((not (equal (FINAL-STATE '(T T T T)) 'T)) nil)
            ((not (equal (FINAL-STATE '(T T T NIL)) 'NIL)) nil)
			(t t)
		)
)