(defun test_PAD1 () (cond 
			((/= (PAD 0) 1) nil)
			((/= (PAD 1) 1) nil)
			((/= (PAD 2) 1) nil)
			((/= (PAD 3) 2) nil)
			((/= (PAD 4) 2) nil)
			((/= (PAD 5) 3) nil)
			((/= (PAD 6) 4) nil)
			((/= (PAD 7) 5) nil)
			((/= (PAD 8) 7) nil)
			((/= (PAD 9) 9) nil)
			((/= (PAD 10) 12) nil)
			((/= (PAD 11) 16) nil)
			((/= (PAD 12) 21) nil)
			((/= (PAD 13) 28) nil)
			((/= (PAD 14) 37) nil)
			(t t)
		)
)

(defun test_PAD2 (N) (cond 
			((/= (PAD N) 1) nil)
			((/= (PAD (+ N 1)) 1) nil)
			((/= (PAD (+ N 2)) 1) nil)
			((/= (PAD (+ N 3)) 2) nil)
			((/= (PAD (+ N 4)) 2) nil)
			((/= (PAD (+ N 5)) 3) nil)
			((/= (PAD (+ N 6)) 4) nil)
			((/= (PAD (+ N 7)) 5) nil)
			((/= (PAD (+ N 8)) 7) nil)
			((/= (PAD (+ N 9)) 9) nil)
			((/= (PAD (+ N 10)) 12) nil)
			((/= (PAD (+ N 11)) 16) nil)
			((/= (PAD (+ N 12)) 21) nil)
			((/= (PAD (+ N 13)) 28) nil)
			((/= (PAD (+ N 14)) 37) nil)
			(t t)
		)
)

(defun test_SUMS1 () (cond 
			((/= (SUMS 0) 0) nil)
			((/= (SUMS 1) 0) nil)
			((/= (SUMS 2) 0) nil)
			((/= (SUMS 3) 1) nil)
			((/= (SUMS 4) 1) nil)
			((/= (SUMS 5) 2) nil)
			((/= (SUMS 6) 3) nil)
			((/= (SUMS 7) 4) nil)
			((/= (SUMS 8) 6) nil)
			((/= (SUMS 9) 8) nil)
			((/= (SUMS 10) 11) nil)
			((/= (SUMS 11) 15) nil)
			((/= (SUMS 12) 20) nil)
			((/= (SUMS 13) 27) nil)
			((/= (SUMS 14) 36) nil)
			(t t)
		)
)

(defun test_SUMS2 (N) (cond 
			((/= (SUMS N) 0) nil)
			((/= (SUMS (+ N 1)) 0) nil)
			((/= (SUMS (+ N 2)) 0) nil)
			((/= (SUMS (+ N 3)) 1) nil)
			((/= (SUMS (+ N 4)) 1) nil)
			((/= (SUMS (+ N 5)) 2) nil)
			((/= (SUMS (+ N 6)) 3) nil)
			((/= (SUMS (+ N 7)) 4) nil)
			((/= (SUMS (+ N 8)) 6) nil)
			((/= (SUMS (+ N 9)) 8) nil)
			((/= (SUMS (+ N 10)) 11) nil)
			((/= (SUMS (+ N 11)) 15) nil)
			((/= (SUMS (+ N 12)) 20) nil)
			((/= (SUMS (+ N 13)) 27) nil)
			((/= (SUMS (+ N 14)) 36) nil)
			(t t)
		)
)

(defun test_ANON () (cond 
            ((not (equal (ANON '42) '?)) nil)
            ((not (equal (ANON 'FOO) '?)) nil)
            ((not (equal (ANON '(((L E) F) T)) '(((? ?) ?) ?))) nil)
            ((not (equal (ANON '(5 FOO 3.1 -0.2)) '(? ? ? ?))) nil)
            ((not (equal (ANON '(1 (FOO 3.1) -0.2)) '(? (? ?) ?))) nil)
            ((not (equal (ANON '(((1 2) (FOO 3.1)) (BAR -0.2))) '(((? ?) (? ?)) (? ?)))) nil)
            ((not (equal (ANON '(R (I (G (H T))))) '(? (? (? (? ?)))))) nil)
			((not (equal (ANON '(1)) '(?))) nil)
			((not (equal (ANON '((1 2) (3 ((4 (5)) (6 7) 8) (9 10)) 11)) '((? ?) (? ((? (?)) (? ?) ?) (? ?)) ?))) nil)
            (t t)
        )
)

